{% set name = "guidance" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9cc0da0f131490719568c3d0284cf9ba66cd087d5b72a1e34d664998ac9472d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - diskcache
    - gptcache
    - openai >=1.0.0
    - pyparsing >=3.0.0
    - pygtrie
    - platformdirs
    - tiktoken >=0.3
    - nest-asyncio
    - msal
    - requests
    - numpy
    - aiohttp
    - ordered-set
    - pyformlang

test:
  imports:
    - guidance
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/microsoft/guidance
  summary: 'A guidance language for controlling large language models'
  description: |
    Guidance enables you to control modern language models more effectively and efficiently
    than traditional prompting or chaining. Guidance programs allow you to interleave generation,
    prompting, and logical control into a single continuous flow matching how the language model
    actually processes the text. Simple output structures like Chain of Thought and its many
    variants (e.g., ART, Auto-CoT, etc.) have been shown to improve LLM performance.
    The advent of more powerful LLMs like GPT-4 allows for even richer structure, and guidance
    makes that structure easier and cheaper.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/guidance

extra:
  recipe-maintainers:
    - johnhany97
