{% set name = "guidance" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99921ef0176fe97565219334dc7246c483170c2fad22e0efd20f3e73490b43fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[all] -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - rust
    - setuptools >=42
    - pybind11 >=2.10.0
    - wheel
  run:
    - python >={{ python_min }}
    # install_requires
    - diskcache
    - numpy
    - ordered-set
    - platformdirs
    - pyformlang
    - protobuf
    - pydantic
    - requests
    - tiktoken >=0.3
    # extra_requires
    ## azureai, openai
    - openai >=1.0.0
    ## schemas
    - jsonschema
    ## server
    - fastapi
    - uvicorn

test:
  imports:
    - guidance
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/guidance-ai/guidance
  summary: 'Guidance is an efficient programming paradigm for steering language models.'
  description: |
    With Guidance, you can control how output is structured and get high-quality output for
    your use case—while reducing latency and cost vs. conventional prompting or fine-tuning.
    It allows users to constrain generation (e.g. with regex and CFGs) as well as to interleave
    control (conditionals, loops, tool use) and generation seamlessly.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/guidance-ai/guidance

extra:
  recipe-maintainers:
    - johnhany97
