{% set name = "guidance" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99921ef0176fe97565219334dc7246c483170c2fad22e0efd20f3e73490b43fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[all] -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    # install_requires
    - diskcache
    - numpy
    - ordered-set
    - platformdirs
    - pyformlang
    - protobuf
    - pydantic
    - requests
    - tiktoken >=0.3
    # extra_requires
    ## azureai, openai
    - openai >=1.0.0
    ## schemas
    - jsonschema
    ## server
    - fastapi
    - uvicorn

test:
  imports:
    - guidance
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/microsoft/guidance
  summary: 'A guidance language for controlling large language models'
  description: |
    Guidance enables you to control modern language models more effectively and efficiently
    than traditional prompting or chaining. Guidance programs allow you to interleave generation,
    prompting, and logical control into a single continuous flow matching how the language model
    actually processes the text. Simple output structures like Chain of Thought and its many
    variants (e.g., ART, Auto-CoT, etc.) have been shown to improve LLM performance.
    The advent of more powerful LLMs like GPT-4 allows for even richer structure, and guidance
    makes that structure easier and cheaper.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/microsoft/guidance

extra:
  recipe-maintainers:
    - johnhany97
